name: Continuous Integration
on: 
  push:
    branches-ignore: 
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Begin linting
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Begin Testing
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Begin Deploy
        uses: actions/checkout@v2
  
      - name: Deploy to development
        uses: amondnet/vercel-action@v20
        id: deploy-vercel-deployment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
    outputs:
      preview-url: ${{ steps.vercel-deployment.outputs.preview-url }}